### ISSUE TITLE
ページの設計図を作る

### ISSUE THREAD

**Issue by ikeda-yuko** [GeekGirls/Cafeniwa#6]

**Comment by ebak0** [comment]
![1](https://cloud.githubusercontent.com/assets/15144134/16563874/7183a844-423f-11e6-8644-c5177708abfb.png)

**Comment by ebak0** [comment]
変更点あれば随時差し替えます

**Comment by ebak0** [comment]
![1](https://cloud.githubusercontent.com/assets/15144134/16573026/38ad24da-42aa-11e6-88c5-8900c090de97.gif)
